add patchStrategy for lists in SPDX document
kubescape/storage pull request #12
Opened 2023-04-27 12:56 UTC by matthyx

should I run something to regenerate some code?

2023-04-27 13:20 UTC, vladklokun commented
Yup, whenever we touch the types, we have to re-generate the code. The procedure is described [here](https://github.com/kubescape/storage#changes-to-the-types).

2023-04-28 07:19 UTC, matthyx commented on pkg/apis/softwarecomposition/v1beta1/spdx_types.go
> +	Relationships []*Relationship `json:"relationships"  patchStrategy:"merge" patchMergeKey:"spdxElementId"`
yes

2023-04-28 12:45 UTC, vladklokun requested changes

2023-04-28 12:45 UTC, vladklokun commented on vendor/modules.txt
> +github.com/go-test/deep
issue: we use `go-cmp` here already, we can use it or `testify/assert`instead of pulling another dependency

2023-04-30 10:43 UTC, Bezbran commented
@avrahams Do you have a solution to "how to test API locally / unitary"?

2023-05-04 14:26 UTC, merged