Generate NP from NetworkNeighborhood
kubescape/storage pull request #120
Opened 2024-06-10 08:53 UTC by dwertent

This is the first step in deprecating the NetworkNeighbors object. Next, we need to adjust the process for generating the NP using kubectl to utilize NetworkNeighborhood instead of NetworkNeighbors. This is somewhat more complex because the scope of a NetworkNeighborhood represents a replica, while the generated NP represents a workload. We'll need to determine the best way to address this. For now, I will not work on that due to time constraints.

2024-06-10 13:06 UTC, matthyx requested changes
check the file known-servewr.yaml if you really wanted to have it, otherwise LGTM

2024-06-10 13:06 UTC, matthyx commented on pkg/apis/softwarecomposition/networkpolicy/v2/networkpolicy.go
> +func listIngressNetworkNeighbors(nn *softwarecomposition.NetworkNeighborhood) []softwarecomposition.NetworkNeighbor {
so this is all the magic happening here :)

2024-06-12 11:36 UTC, dwertent commented on known-servewr.yaml
> +apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
I will change the server name. But I committed this for the test...

2024-06-17 07:46 UTC, matthyx approved these changes

2024-06-17 11:48 UTC, merged