Summary api objects
kubescape/storage pull request #32
Opened 2023-08-09 12:23 UTC by rcohencyberarmor

change the VulnerabilityManifestSummarySpec as represent in the following link:
https://cyberarmor-io.atlassian.net/wiki/spaces/RD/pages/216727553/Summary+vuln+object+CRD+modification

2023-08-09 14:12 UTC, vladklokun commented on artifacts/vulnerabilitymanifestsummaries/01-example.yaml
> +
style: missing proper trailing newline

This is probably because your editor saves newlines as CRLF. Try using LF.

2023-08-10 06:44 UTC, dwertent requested changes
Please notice the changes I made to the CRD format

2023-08-10 06:44 UTC, dwertent commented on artifacts/vulnerabilitymanifestsummaries/01-example.yaml
> +  vulnerabilities:
```suggestion
  vulnerabilitiesRef:
```

2023-08-10 06:44 UTC, dwertent commented on artifacts/vulnerabilitymanifestsummaries/01-example.yaml
> +    basic:
```suggestion
    all:
```

2023-08-10 06:44 UTC, dwertent commented on artifacts/vulnerabilitymanifestsummaries/01-example.yaml
> +    filtered:
```suggestion
    relevant: 
```

2023-08-10 14:32 UTC, vladklokun approved these changes
LGTM

2023-08-10 14:35 UTC, dwertent approved these changes

2023-08-10 14:35 UTC, merged