Support scoped configuration scan summary types
kubescape/storage pull request #39
Opened 2023-08-22 13:35 UTC by Daniel-GrunbergerCA

Add two type definitions:

1. `ScopedConfigurationScanSummary` - Represents an summary of `WorkloadConfigurationScanSummary` objects, aggregated for an specific scope, such as namespace / cluster
2. `ScopedConfigurationScanSummaryList` - Represents an list of `ScopedConfigurationScanSummary` objects

2023-08-22 14:18 UTC, vladklokun approved these changes
Type definitions and registrations look good to me.

2023-08-29 12:23 UTC, Daniel-GrunbergerCA commented on pkg/registry/file/configurationscansummarystorage.go
> +	}
We aren't sure how to create proper custom errors, current behavior of key not found is acceptable, so skipping it for now

2023-08-29 12:24 UTC, Daniel-GrunbergerCA commented on pkg/registry/file/configurationscansummarystorage.go
> +	configurationScanSummaryObj := buildConfigurationScanSummary(*workloadScanSummaryListObjPtr, namespace)
thanks :)

2023-08-29 12:46 UTC, vladklokun requested changes
Let’s make the changes we discussed, and this is good to go. Good job!

2023-08-30 13:00 UTC, vladklokun approved these changes
Change the OS filesystem to an in-memory one and we’re good to go. Thank you for your hard work! :)

2023-08-30 15:23 UTC, vladklokun approved these changes
Please remember to make a meaningful merge commit message.

2023-08-30 16:14 UTC, merged